# Site settings
title: Computational Microscopy Group
email: philipp.pelz@fau.de
webmaster: Philipp Pelz
description: "Computational Microscopy Group"
# No need for user/organization github pages, and localhost,
# but deployment on organization server requires
# subdirectory "/Astro"
#baseurl:
#url:

timezone: Europe/Berlin

# Build settings
markdown: kramdown
permalink: pretty
destination: ../loc_version

# Exclude
# See https://jekyllrb.com/docs/troubleshooting/#configuration-problems

exclude: 
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - Rakefile
  - summat.sh
  - conferences/_posts/en/yml2tex_output/
  - conferences/_posts/ja/yml2tex_output/

# Include
include:
  - .htaccess

# Collections
collections:
  members:
    output: true

# Defaults for categories
defaults:
  -
    scope:
      path: ""
    values:
      lang: en
  -
    scope:
      path: seminars
    values:
      layout: single_seminar
  -
    scope:
      path: news
    values:
      layout: single_news
  -
    scope:
      path: achievements
    values:
      layout: single_achievement
  -
    scope:
      path: conferences
    values:
      layout: single_conference
  -
    scope:
      path: projects
    values:
      layout: single_project
  -
    scope:
      path: featured
    values:
      layout: single_featured
  -
    scope:
      path: members
    values:
      layout: redirect_back


